apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: task-pal
build:
  local:
    push: false
    useDockerCLI: false
  artifacts:
    - image: ghcr.io/ammbra/task-pal
      custom:
        buildCommand: ./mvnw verify -Ddekorate.docker.auto-build-enabled=true -Ddekorate.docker.image=localhost:5000/task-pal
        dependencies:
          paths:
            - target
      sync:
        manual:
          - src: "target/task-pal.jar"
            dest: task-pal.jar
manifests:
  rawYaml:
    - k8s/kubernetes.yml
profiles:
  - name: dev
    build:
      artifacts:
        - image: ghcr.io/ammbra/task-pal  # Development image for Rancher Desktop
  - name: prod
    build:
      artifacts:
        - image: ghcr.io/ammbra/task-pal  # Development image for Rancher Desktop
          docker:
            dockerfile: Dockerfile